### PR TITLE
Feature/acorn csp support

### PR DESCRIPTION
**Pull request by call-a3**
One of the features in #40, seperated into a seperate branch

### CODE REVIEW

**Comment by call-a3** [comment]
@ForbesLindesay @substack Could this be merged? It's the same features as in #40, only split into different PRs (as substack requested).

**Comment by substack** [comment]
This patch also touches every line in the file moving source over to `core.js` for no reason.

**Comment by substack** [comment]
OK I understand the reason for this only after digging through acorn issues to find what the CSP issue is even about. A link would have been helpful to establish context!

**Comment by call-a3** [comment]
Sorry, I should have thought of that. I'm glad you figured it out when you did though. It is/was making working with node-falafel on travis impossible.

**Comment by goto-bus-stop** [comment]
Looks like this is no longer necessary for new acorn versions. Thanks for submitting a patch, sorry that this has sat for so long!

**Pull request closed without merging**
