### PR TITLE
Fix globules, update acorn

### PR DESCRIPTION
**Pull request by dfcreative**
Hi @substack!
There are tests, fixed for shells without globs.
Also there is an important update of acorn dep, which is the case of glslify https://github.com/stackgl/glslify/issues/68
Please review and merge

### CODE REVIEW

**Comment by dfcreative** [comment]
@substack was that PR noticed?

**Comment by dfcreative** [comment]
@substack hi, what preventing it from merging? It blocks glslify with ES6.

**Comment by prabhu** [comment]
Another sad npm package which is quite heavily used but not getting maintained properly. I wish there is a charity for all such orphaned packages.

**Comment by msaglietto** [comment]
I dont know why I am a contributor for this project but if I have this kind of power and I see the test pass and a problem solved I think is ok to merge it .. so thanks you @dfcreative

**Comment by dfcreative** [comment]
@msaglietto thanks a lot, very kind of you. But to get dependent projects fixed it also requires bumping npm version. Can you publish npm patch?

**Comment by msaglietto** [comment]
@dfcreative Sry, I think I cant help you with that ... 

>  npm ERR! you do not have permission to publish "falafel"

**Comment by dfcreative** [comment]
@bobthecow @nanodeath @alltom @eugeneware hello gentlemen, could you help with publishing updated falafel on npm?

**Pull request merged**
